# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOwcWe9a3pceFUz0ZPb4AaFWBVUN44zX
"""

#logical Operators
temp = 25
is_raining = False

if temp > 35 or temp < 0 or is_raining:
  print("The outdoor event is cancelled")
else:
  print("The outdoor event is not cancelled")


#and operator

if temp>=25 and temp<=35 and not is_raining:
  print("The outdoor event is cancelled")
else:
  print("The outdoor event is not cancelled")

"""#while loops

"""

name = input("enter your name: ")

while name == "":
  name = input("Enter your name: ")
age = int(input("Enter your age: "))
while age < 0:
  print("Invalid age")
  age = int(input("Enter your age: "))
print(f"Hello {name}")

#for loop
print("Starts with 0")
for i in range(10):
  print(i)

print("Starts with 1")
for i in range (1,11):
  print(i)

print("Increasing value +2")
for i in range(1,11,2):
  print(i)

name = "Salah Uddin Selim"
for letter in name:
  print(letter, end = " ")

for i in range(10,0,-1):
  print(i)
print("Happy new year")

import time
for i in range (10,0,-1):
  print(i)
  time.sleep(1)
print("HAPPY NEW YEAR")

#list [] =  most flexible

fruites = ["apple", "banana", "cherry"]
print(fruites)
print(fruites[0])
for fruit in fruites:
  print(fruit, end = " ")
print()
fruites.append("orange")
print(fruites)
fruites.remove("banana")
print(fruites)

#tuple = not flexible can't change the values
fruits = ("apple", "banana", "cherry")
print(fruits)
print(fruits[0])
for fruit in fruits:
  print(fruit, end = " ")

#set = mutable, unordered, no duplicates, best for membership testing
fruites = {"apple", "banana", "cherry"}
print(fruites)
fruites.add("orange")
print(fruites)
fruites.remove("banana")
print(fruites)
print("banana" in fruites)