# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvN2mMWAsKvJk2FbAWt8j5Um_lucUFQ1
"""

#function
def happyBirthday():
  print("Happy Birthday to you!")

happyBirthday()

def happyBirthday(name):
  print("Happy Birthday to you!")
  print("Happy Birthday to you!")
  print("Happy Birthday, dear " + name)
  print("Happy Birthday to you!")

happyBirthday("Bob")

def happyBirthday(name, age):
  print("Happy Birthday to you!")
  print("Happy Birthday to you!")
  print("Happy Birthday, dear " + name)
  print("Happy Birthday to you!")
  print("You are " + str(age) + " years old!")
  print("Happy Birthday to you!")

happyBirthday("Bob", 25)

def display_invoice(username, amount, due_date):
  print("Hello " + username)
  print("Thank you for your purchase!")
  print("Your invoice total is $" + str(amount))
  print("It will be due on " + due_date)

display_invoice("Bob", 100, "01/01/2023")

#return statement
def add(a, b):
  return a + b

result = add(1, 2)
print(result)

def create_name(first_name, last_name):
  full_name = first_name.capitalize() + " " + last_name.capitalize()
  return full_name
full_name =create_name("bob", "smith")
print(full_name)