# -*- coding: utf-8 -*-
"""oops_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMRVocWn1EMz78pqqtZHlFVjNbFWpu80
"""

#Class & Instance
class student:
  college_name = "UIU" #class attribute

  def __init__(self,name,id):
    self.name = name #object attribute
    self.id = id
  def helloStudent(self):
    print("Hello Student")
s1 = student("A",1)
s2 = student("B",2)
print(s1.college_name)
print(s2.college_name)
print(s1.name)
s1.helloStudent()

#class attribute < object attribute when both got the same name

from re import A
from typing import Self
#practice question
class Student:
  def __init__(self, name, marks):
    self.name = name
    self.marks = marks

  def avgMark(self):
    sum = 0
    for mark in self.marks:
      sum += mark
    avg = sum/3
    print(f"The avg of the student is : {avg}")

s1 = Student("A", [1,2,3])
s1.avgMark()

#static Method (don't use the self method)
class Student:
  @staticmethod #decorator
  def hello():
    print("Hello Student")
#direct apply
print("Class Method")
Student.hello()
print("Object Method")
s1 = Student()
s1.hello()