# -*- coding: utf-8 -*-
"""OOPs_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FoAs94jTxFq1M7_zFs15A_ujysfeRsYd
"""

#class create
class Student:
  name = "Salah Uddin"


#creating objects(instance of class)
s1 = Student()
print(s1)

#value
print(s1.name)

#new class
class Car:
  color = "blue"
  brand = "mercedes"
car1 = Car()
print(car1.color)
print(car1.brand)

#Constructor(always create a __init__(self) function always(even we don't create it))
class Car:
  def __init__(self, name):
    print("I am a constructor")
    print(self)
    print(name)

car1 = Car("Salah uddin selim")

class Student:
  def __init__(self, name):
    print("I am a constructor")
    self.name = name #adding new attributes in the class

s1 = Student("Salah Uddin")
print(s1.name)