# -*- coding: utf-8 -*-
"""OOPs_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucHKTgZePQTIbGW4xXqbVIj7VCL0V8Mb
"""

#Abstraction hides unnecessary things from the user (init)
class Car:
  def init(self):
    self.acc = False
    self.brk = False
    self.clutch = False
  def Start(self):
    self.clutch = True
    self.acc = True
    print("Car started....")

car1 = Car()
car1.Start()