# -*- coding: utf-8 -*-
"""python_DS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhmlmvG22hREwo9mpxyQvvWwhcvGtSTs
"""



print("I love Biriyani")

print("It's really good!")
#this is my first python code

#variable
#string
full_name = "Salah Uddin Selim"
print(f"Hello {full_name}")
#integer
age = 25
print(f"You are {age}")
#float
cgpa = 3.94
print(f"Your cgpa is : {cgpa}")
#boolean
is_student = True
print(f"Are you a student? {is_student}")

number= 10
print(number**2)

#type conversion(casting)
name ="Salah Uddin Selim"
age = 25
cgpa = 3.74
is_student = True
print(type(name))
age = float(age)
print(type(age))
age = str(age)
print(type(age))
age+="1"
print(age)
name = bool(name)
print(name)
print(type(name))

#userinput
name = input("Enter your name: ")
print(f"Hello {name}")

age = int(input("Enter you age: "))
print(f"You are {age} years old")

#conditions
age = int(input("Enter your age: "))
if age >18:
  print("You are adult")
elif age >=13 and age<=18:
  print("You are teenage")
else:
  print("You are small")